### ISSUE TITLE
Only BT method works for "put" options getPrice()

### ISSUE THREAD

**Issue by leoplusx** [QSCTech-Sange/option-price#2]
Thank your for the great library!

I noticed that the getPrice() function will output "None" if the option kind is "put", unless the method is specified as BT. Both other methods (MC and BSM) won't work.

**Comment by QSCTech-Sange** [comment]
That's true since MC and BSM can't be used under "put" options' circumstance in the first place. The reason behind that is related to the algorithm and the idea of these methods.




Hope you enjoy :)


-----原始邮件-----
发件人:leobaumgardt <notifications@github.com>
发送时间:2020-09-04 23:59:12 (星期五)
收件人: QSCTech-Sange/option-price <option-price@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [QSCTech-Sange/option-price] Only BT method works for "put" options getPrice() (#2)






Thank your for the great library!

I noticed that the getPrice() function will output "None" if the option kind is "put", unless the method is specified as BT. Both other methods (MC and BSM) won't work.

**Comment by leoplusx** [comment]
Ah, I see. So it's a feature, not a bug. Thanks for clarifying!

Thanks for making the library and sharing it 👍
